name: Re-Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The minecraft version to re-release'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew publish refreshMeta --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          FORCE_PUBLISH: ${{ github.event.inputs.version }}
          META_UPDATE_URL: ${{ secrets.META_UPDATE_URL }}
